"""
TrySentry - HTML incident report
Generates a self-contained HTML report from alerts.
"""
import json
import time
from pathlib import Path
from typing import List

from .. import logger


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>TrySentry Report</title>
<style>
  :root {
    --bg: #0f1117;
    --card: #1a1d29;
    --border: #2a2f3f;
    --text: #d8dee9;
    --muted: #8892a0;
    --blue: #4cc9f0;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 40px 20px;
    background: var(--bg); color: var(--text);
    font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
    line-height: 1.5;
  }
  .container { max-width: 1100px; margin: 0 auto; }
  header {
    padding-bottom: 20px;
    border-bottom: 1px solid var(--border);
    margin-bottom: 30px;
  }
  h1 { margin: 0 0 8px; font-size: 28px; color: var(--blue); }
  h2 { font-size: 20px; margin: 30px 0 12px; color: var(--blue); }
  .meta { color: var(--muted); font-size: 13px; }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 12px; margin: 20px 0;
  }
  .stat {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 8px; padding: 16px; text-align: center;
  }
  .stat .num {
    font-size: 32px; font-weight: bold; color: var(--blue);
    display: block;
  }
  .stat .lbl {
    color: var(--muted); font-size: 12px;
    text-transform: uppercase;
  }
  table {
    width: 100%; border-collapse: collapse;
    background: var(--card); border: 1px solid var(--border);
    border-radius: 8px; overflow: hidden;
    margin-bottom: 20px; font-size: 14px;
  }
  th, td {
    padding: 10px 12px; text-align: left;
    border-bottom: 1px solid var(--border);
  }
  th {
    background: #14171f; color: var(--muted);
    font-weight: 600; font-size: 12px;
    text-transform: uppercase;
  }
  tr:last-child td { border-bottom: none; }
  tr:hover { background: #1f2330; }
  code {
    background: #14171f; padding: 2px 6px;
    border-radius: 4px; color: var(--blue); font-size: 13px;
  }
  footer {
    margin-top: 40px; padding-top: 20px;
    border-top: 1px solid var(--border);
    text-align: center; color: var(--muted); font-size: 12px;
  }
  .sev-critical { color: #ff6b6b; font-weight: 600; }
  .sev-high     { color: #ffa94d; font-weight: 600; }
  .sev-medium   { color: #ffd43b; font-weight: 600; }
  .sev-low      { color: var(--blue); font-weight: 600; }
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>TrySentry Incident Report</h1>
    <div class="meta">Generated: {generated_at}</div>
  </header>

  <h2>Summary</h2>
  <div class="summary">
    <div class="stat">
      <span class="num">{total}</span>
      <span class="lbl">Total Alerts</span>
    </div>
    <div class="stat">
      <span class="num">{critical}</span>
      <span class="lbl">Critical</span>
    </div>
    <div class="stat">
      <span class="num">{high}</span>
      <span class="lbl">High</span>
    </div>
    <div class="stat">
      <span class="num">{medium}</span>
      <span class="lbl">Medium</span>
    </div>
    <div class="stat">
      <span class="num">{low}</span>
      <span class="lbl">Low</span>
    </div>
  </div>

  <h2>Alerts</h2>
  {alerts_table}

  <footer>
    Generated by TrySentry v1.0 &nbsp;|&nbsp;
    Endpoint Detection & Response
  </footer>
</div>
</body>
</html>
"""


def _alerts_table(alerts: List[dict]) -> str:
    if not alerts:
        return "<p>No alerts recorded.</p>"

    rows = []
    for a in alerts:
        sev = a.get("severity", "low")
        t = time.strftime("%Y-%m-%d %H:%M:%S",
                          time.localtime(a.get("_stored_at", time.time())))
        mitre = a.get("mitre", {})
        mitre_id = mitre.get("id", "")
        ev = a.get("event", {})
        proc = ev.get("Image", "-")

        rows.append(
            f"<tr>"
            f"<td><span class='sev-{sev}'>{sev}</span></td>"
            f"<td>{a.get('score', 0)}</td>"
            f"<td>{a.get('title', '')}</td>"
            f"<td><code>{mitre_id}</code></td>"
            f"<td><code>{proc}</code></td>"
            f"<td>{t}</td>"
            f"</tr>"
        )

    return (
        "<table>"
        "<thead><tr>"
        "<th>Severity</th><th>Score</th><th>Rule</th>"
        "<th>MITRE</th><th>Process</th><th>Time</th>"
        "</tr></thead>"
        "<tbody>" + "".join(rows) + "</tbody>"
        "</table>"
    )


def generate(alerts: List[dict], out_path: str = "report.html"):
    """Generate an HTML report from a list of alerts."""
    counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
    for a in alerts:
        sev = a.get("severity", "low")
        counts[sev] = counts.get(sev, 0) + 1

    html = HTML_TEMPLATE.format(
        generated_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        total=len(alerts),
        critical=counts["critical"],
        high=counts["high"],
        medium=counts["medium"],
        low=counts["low"],
        alerts_table=_alerts_table(alerts),
    )

    Path(out_path).write_text(html, encoding="utf-8")
    logger.ok(f"Report written: {out_path}")
    return out_path
